### ISSUE TITLE
Check that a script tag inserted via innerHTML does not execute

### ISSUE THREAD

**Issue by leodido** [leogr/dom-deque#10]
Spec [here](https://www.w3.org/TR/2008/WD-html5-20080610/dom.html#innerhtml0).

**Comment by leogr** [comment]
A `<template>`'s content populated via `innerHTML` has no side effects since `<script>` elements inserted using `innerHTML` do not execute when they are inserted (by specs). 
When the `<template>` stamps, the `<template>`'s instance is imported into the DOM and `<script>` elements execute, that's the wanted behaviour.
